version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-thapp
    environment:
      POSTGRES_DB: THDB
      POSTGRES_USER: THUSYSRTR
      POSTGRES_PASSWORD: TH:124578
    ports:
      - "3415:5432"
    volumes:
      - pgdata_thapp_dev:/var/lib/postgresql/data
    networks:
      - thapp-be

volumes:
  pgdata_thapp_dev:
    driver: local

networks:
  thapp-be:
    driver: bridge